services:
  djet-corporate-back:
    image: joolinternational/joolhub:djet-corporate-1.0.0y-latest
    restart: always
    container_name: "djet-corporate-back"
    ports:
      - "8012:8012"
    volumes:
      - djetcorporate:/datastore/djet-corporate
    networks:
      - djetcorporatenetwork

  djet-corporate-front:
    image : joolinternational/joolhub:djet-corporate-frontend-1.0.0a-latest
    restart: always
    container_name: "djet-corporate-front"
    depends_on:
      - djet-corporate-back
    ports:
      - "5000:5000"
    volumes:
      - djetcorporate:/datastore/djet-corporate
    networks:
      - djetcorporatenetwork

networks:
  djetcorporatenetwork:
    external: true


volumes:
  djetcorporate:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /datastore/djet-corporate